APP_ENV: dev
APP_API_VERSION: 0.0.1
SERVER_HOST: 0.0.0.0
SERVER_PORT: 8000

# JWT Configuration
JWT_SECRET_KEY: "dev-super-secret-jwt-key-change-in-production"
JWT_ALGORITHM: "HS256"
JWT_EXPIRY_HOURS: 12

# API Key Configuration
API_KEY_LENGTH: 32
API_KEY_PREFIX: "mai_"

# Debug Configuration
DEBUG: "true"
DEBUG_VERBOSE: 3 # 1=minimal, 2=normal, 3=verbose

# Email Configuration
SMTP_HOST: smtp.gmail.com
SMTP_PORT: 587
SMTP_USERNAME: ${SMTP_USERNAME}  # Loaded from .env file
SMTP_PASSWORD: ${SMTP_PASSWORD}  # Loaded from .env file
SMTP_USE_TLS: true
SMTP_SENDER_NAME: "MAI Scam Detection"
REPORT_EMAIL: report.maiscam@gmail.com
